apiVersion: v1
kind: Service
metadata:
    name: cs3219-db
    labels:
        app: cs3219-db
    namespace: cs3219-db
spec:
    selector:
        app: cs3219-db
    type: NodePort
    ports:
        - port: 3306
          targetPort: 3306
          nodePort: 31000
          name: cs3219-db
